/* ----------------
	 DEPENDENCIES
----------------- */
const
	express = require('express'),
	router  = require('./routes'),
	{auth}  = require('express-openid-connect'),
	_path   = require('path'),
	https 	= require('https'),
	jwt     = require('express-jwt'),
	fs 			= require('fs'),
	app     = express(),
	engine  = require('ejs-locals');
						require('dotenv').config();


/* ----------------
	 CONFIGURATION
----------------- */

const
	audience       = process.env.AUD || 'https://mascustest.mascus.com/',
	issuer         = process.env.ISS || 'https://dev-id.ritchiebros.com/',
	issuerBaseURL  = process.env.ISSUER_BASE_URL || 'https://dev-id.ritchiebros.com/',
	baseURL        = process.env.BASE_URL || 'https://rid-auth0-poc.herokuapp.com/',
	clientID       = process.env.CLIENT_ID || 'NtLGXEBkuMzejJxHXVaUNCkNVxuLAaBO',
	secret         = process.env.SECRET || 'fuRSxZlyN1m9aVZ6U7W5QaMJj8ul_JqPFGOpFmh-H9Lfj0l2B32G0109Zo_X3iDj',
	jwtCheckConfig = jwt({secret, audience, issuer, algorithms: ['RS256']}).unless({path: ['/', '/profile']}),// Middleware used to authenticate the access tokens generated by Auth0 and sent in the Authorization header of each request
	authConfig     = {baseURL, clientID, secret, issuerBaseURL, idpLogout: true,authRequired: false, auth0Logout: true};// Middleware used to retrieve user data and handle the Auth0 authentication flows


/* ----------------
	MIDDLEWARE
	----------------- */
app.use(auth(authConfig))
app.use(jwtCheckConfig)
app.use(function (req, res, next) { res.locals.user = req.oidc.user; next(); })
app.use('/', router)
app.use(function (err, req, res, next) { res.status(err.status).render('error', { status: err.status, message: err.message, error: err }); });


/* ----------------
	 SETUP
----------------- */
const port = process.env.PORT || 3000;
const successLog = () => { console.log('Application running on port ' + port) };


app.use(express.json())
	.set('view engine', 'ejs')
	.engine('ejs', engine)
	.set('views', _path.join(__dirname, 'views'))
	.use(express.static(_path.join(__dirname, 'public')))

	.listen(port, successLog);
// // For local setup: Comment line above — uncomment all below
// const key = fs.readFileSync('certs/server.key', 'utf8');
// const cert = fs.readFileSync('certs/server.crt', 'utf8');
// https.createServer({ key, cert }, app)
// 	.listen(port, successLog);
